/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.UserAccount.User;
import Business.UserAccount.User.Role;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author kanheshreya
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel activePanel=null;

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel() {
        initComponents();
        //person= new BasicInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Managers", "Delivery Men", "Customers", "Restaurants" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("System Admin Dashboard");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage User type");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View All");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(createButton)
                .addGap(12, 12, 12)
                .addComponent(updateButton)
                .addGap(14, 14, 14)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(viewButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String type = jComboBox1.getSelectedItem().toString();
            if(activePanel!=null) remove(activePanel);
        revalidate();
        repaint();
        if(type.equals("Managers")){
            activePanel = new Create_RestaurantManagerJPanel();
        }
        else if(type.equals("Restaurants")){
            activePanel = new CreateRestaurant();
        }
        else if(type.equals("Customers")){
            activePanel = new Create_CustomerJPanel();
        }
        else if(type.equals("Delivery Men")){
            activePanel = new Create_DeliveryMenJPanel();
        }
        activePanel.setBounds(200, 10, 273, 196);
        activePanel.setSize(400, 300);
        this.add(activePanel);
        revalidate();
    }//GEN-LAST:event_createButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String type = jComboBox1.getSelectedItem().toString();
        if(activePanel!=null) remove(activePanel);
        revalidate();
        repaint();
        if(type.equals("Managers")){
            activePanel = new Update_RestaurantManagerJPanel();
        }
        else if(type.equals("Restaurants")){
            activePanel = new UpdateRestaurantJPanel();
        }
        else if(type.equals("Customers")){
            activePanel = new Update_CustomerJPanel();
        }
        else if(type.equals("Delivery Men")){
            activePanel = new Update_DeliveryMenJPanel();
        }
        activePanel.setBounds(200, 10, 273, 196);
        activePanel.setSize(400, 300);
        this.add(activePanel);
        revalidate();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String type = jComboBox1.getSelectedItem().toString();
        if(activePanel!=null) remove(activePanel);
        revalidate();
        repaint();
        if(type.equals("Managers")){
            activePanel = new Delete_RestaurantManagerJPanel();
        }
        else if(type.equals("Restaurants")){
            activePanel = new DeleteRestaurantJPanel();
        }
        else if(type.equals("Customers")){
            activePanel = new Delete_CustomerJPanel();
        }
        else if(type.equals("Delivery Men")){
            activePanel = new Delete_DeliveryMenJPanel();
        }
        activePanel.setBounds(200, 10, 273, 196);
        activePanel.setSize(400, 300);
        this.add(activePanel);
        revalidate();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        if(activePanel!=null) remove(activePanel);
        revalidate();
        repaint();
        String type = jComboBox1.getSelectedItem().toString();
        if(type.equals("Managers")){
            activePanel = new viewJPanel(Role.Manager);
        }
        else if(type.equals("Customers")){
            activePanel = new viewJPanel(Role.Customer);
        }
        else if(type.equals("Delivery Men")){
        activePanel = new viewJPanel(Role.DeliveryMan);
        }
        else{
          activePanel = new viewJPanel(null);  
        }
        
        activePanel.setBounds(200, 10, 273, 196);
        activePanel.setSize(400, 300);
        this.add(activePanel);
        
        revalidate();
        
    }//GEN-LAST:event_viewButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
