/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import userinterface.RestaurantAdminRole.*;
import Business.pojo.Item;
import Business.pojo.Order;
import java.util.List;

/**
 *
 * @author visha
 */
public class OrderDetailsPopup extends javax.swing.JPanel {

    /**
     * Creates new form OrderDetailsPopup
     */
    public OrderDetailsPopup(Order order) {
        initComponents();
        jTextField1.setText(""+order.getId());
        jTextField2.setText(""+order.getCustomer().getLastName());
        jTextField9.setText(""+order.getCustomer().getAddress());
        jTextField3.setText(""+order.getStatus());
        if(order.getDeliveryMan()!=null)
            jTextField4.setText(""+order.getDeliveryMan().getLastName());
        jTextField5.setText(""+order.getTimePlaced());
        jTextField6.setText(""+order.getTimeCompleted());
        jTextField7.setText(""+order.getComment());
        List<Item> temp = order.getItems();
        float total = 0f;
        for(Item i : temp){
            total+=i.getPrice();
            jTextArea1.append(i.getName()+"\n");
        }
        jTextField8.setText(""+total);
        jLabel12.setText("Restaurant - "+order.getRestaurant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 61, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Last Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 86, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 142, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DeliveryMan Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time Placed :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 198, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time Completed :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 229, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Comments : ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 254, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Your Order Details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Value :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 285, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Items :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 310, -1, -1));

        jTextField1.setEditable(false);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 58, 160, -1));

        jTextField2.setEditable(false);
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 86, 160, -1));

        jTextField3.setEditable(false);
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 142, 160, -1));

        jTextField4.setEditable(false);
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, -1));

        jTextField5.setEditable(false);
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 198, 160, -1));

        jTextField6.setEditable(false);
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 226, 160, -1));

        jTextField7.setEditable(false);
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 254, 160, -1));

        jTextField8.setEditable(false);
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 282, 160, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(10);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 160, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 117, -1, -1));

        jTextField9.setEditable(false);
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 114, 160, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Restaurant  ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
