/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import model.lab1;

/**
 *
 * @author visha
 */
public class Address extends javax.swing.JPanel {

    /**
     * Creates new form Address
     */
    lab1 product;
    public Address(lab1 product) {
        initComponents();
        
        this.product =product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        streetaddress = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        zipcode = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        Tstreetaddress = new javax.swing.JTextField();
        Tzipcode = new javax.swing.JTextField();
        Tstate = new javax.swing.JTextField();
        Tcity = new javax.swing.JTextField();
        addsave = new javax.swing.JButton();

        streetaddress.setText("street address");

        city.setText("city");

        state.setText("state");

        zipcode.setText("zip code");

        header.setText("Address information");

        Tstreetaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TstreetaddressActionPerformed(evt);
            }
        });

        Tstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TstateActionPerformed(evt);
            }
        });

        Tcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcityActionPerformed(evt);
            }
        });

        addsave.setText("Save");
        addsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zipcode)
                                .addGap(200, 200, 200)
                                .addComponent(Tzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(streetaddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(city)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tcity, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(state)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tstate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(header)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(addsave)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(streetaddress)
                    .addComponent(Tstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(city)
                    .addComponent(Tcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(state)
                    .addComponent(Tstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipcode)
                    .addComponent(Tzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(addsave)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TstreetaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TstreetaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TstreetaddressActionPerformed

    private void TstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TstateActionPerformed

    private void TcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcityActionPerformed

    private void addsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsaveActionPerformed
        // TODO add your handling code here
        
        product.setStreetaddress(Tstreetaddress.getText());
        product.setCity(Tcity.getText());
        product.setState(Tstate.getText());
        product.setZipcode(Tzipcode.getText());
        
        JOptionPane.showMessageDialog(this,"Saved!!");
     
        
     
    }//GEN-LAST:event_addsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tcity;
    private javax.swing.JTextField Tstate;
    private javax.swing.JTextField Tstreetaddress;
    private javax.swing.JTextField Tzipcode;
    private javax.swing.JButton addsave;
    private javax.swing.JLabel city;
    private javax.swing.JLabel header;
    private javax.swing.JLabel state;
    private javax.swing.JLabel streetaddress;
    private javax.swing.JLabel zipcode;
    // End of variables declaration//GEN-END:variables
}
