/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.lab1;

/**
 *
 * @author visha
 */
public class checkingview extends javax.swing.JPanel {

    /**
     * Creates new form checkingview
     */
    lab1 product;
    public checkingview(lab1 product) {
        initComponents();
        
        this.product = product;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkingviewheader = new javax.swing.JLabel();
        VCBankname = new javax.swing.JLabel();
        VCbankroutingnumber = new javax.swing.JLabel();
        VCbankaccountnumber = new javax.swing.JLabel();
        VCaccountbalance = new javax.swing.JLabel();
        VCaccounttype = new javax.swing.JLabel();
        TCbankname = new javax.swing.JLabel();
        TCbankroutingnumber = new javax.swing.JLabel();
        TCbankaccountnumber = new javax.swing.JLabel();
        TCaccountbalance = new javax.swing.JLabel();
        TCaccounttype = new javax.swing.JLabel();

        checkingviewheader.setText("Checking account information");

        VCBankname.setText("Bank name");

        VCbankroutingnumber.setText("bank routing number");

        VCbankaccountnumber.setText("bank account number");

        VCaccountbalance.setText("account balance");

        VCaccounttype.setText("account type ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TCaccounttype))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VCbankaccountnumber)
                            .addComponent(VCaccountbalance)
                            .addComponent(VCaccounttype)
                            .addComponent(VCbankroutingnumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCbankroutingnumber)
                            .addComponent(TCaccountbalance)
                            .addComponent(TCbankaccountnumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VCBankname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TCbankname)
                        .addGap(7, 7, 7)))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(checkingviewheader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkingviewheader, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCBankname)
                    .addComponent(TCbankname))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCbankroutingnumber)
                    .addComponent(TCbankroutingnumber))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCbankaccountnumber)
                    .addComponent(TCbankaccountnumber))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCaccountbalance)
                    .addComponent(TCaccountbalance))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCaccounttype)
                    .addComponent(TCaccounttype))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TCaccountbalance;
    private javax.swing.JLabel TCaccounttype;
    private javax.swing.JLabel TCbankaccountnumber;
    private javax.swing.JLabel TCbankname;
    private javax.swing.JLabel TCbankroutingnumber;
    private javax.swing.JLabel VCBankname;
    private javax.swing.JLabel VCaccountbalance;
    private javax.swing.JLabel VCaccounttype;
    private javax.swing.JLabel VCbankaccountnumber;
    private javax.swing.JLabel VCbankroutingnumber;
    private javax.swing.JLabel checkingviewheader;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        
    
        TCbankname.setText(product.getCBankname());
        TCbankaccountnumber.setText(product.getCbankaccountnumber());
        TCbankroutingnumber.setText(product.getCbankrouatingnumber());
        TCaccountbalance.setText(product.getCaccountbalance());
        TCaccounttype.setText(product.getCaccounttype());
                
    
    
    }
}
