/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import model.lab1;

/**
 *
 * @author visha
 */
public class Checking extends javax.swing.JPanel {

    /**
     * Creates new form Checking
     */
    lab1 product;
    public Checking(lab1 product) {
        initComponents();
        
        this.product =product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkingheader = new javax.swing.JLabel();
        CcBANKname = new javax.swing.JLabel();
        Ccbankroutingnumber = new javax.swing.JLabel();
        Ccbankaccountnumber = new javax.swing.JLabel();
        Ccaccountbalance = new javax.swing.JLabel();
        Ccaccounttype = new javax.swing.JLabel();
        TCcBankname = new javax.swing.JTextField();
        TCcbankroutingnumber = new javax.swing.JTextField();
        TCcbankaccountnumber = new javax.swing.JTextField();
        TCcaccountbalance = new javax.swing.JTextField();
        TCcaccounttype = new javax.swing.JTextField();
        checksave = new javax.swing.JButton();

        checkingheader.setText("Checking account information");

        CcBANKname.setText("Bank name");

        Ccbankroutingnumber.setText(" bank routing number");

        Ccbankaccountnumber.setText("bank account number");

        Ccaccountbalance.setText("account balance");

        Ccaccounttype.setText("account type ");

        TCcBankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCcBanknameActionPerformed(evt);
            }
        });

        TCcbankroutingnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCcbankroutingnumberActionPerformed(evt);
            }
        });

        TCcbankaccountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCcbankaccountnumberActionPerformed(evt);
            }
        });

        TCcaccountbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCcaccountbalanceActionPerformed(evt);
            }
        });

        TCcaccounttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCcaccounttypeActionPerformed(evt);
            }
        });

        checksave.setText("Save");
        checksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checksaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(checkingheader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CcBANKname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ccaccounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ccaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ccbankaccountnumber)
                            .addComponent(Ccbankroutingnumber))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCcbankroutingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCcbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCcaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCcaccounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TCcBankname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(checksave)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkingheader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CcBANKname))
                    .addComponent(TCcBankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ccbankroutingnumber)
                            .addComponent(TCcbankroutingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ccbankaccountnumber)
                            .addComponent(TCcbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Ccaccountbalance)
                        .addGap(18, 18, 18)
                        .addComponent(Ccaccounttype))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TCcaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TCcaccounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(checksave)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TCcBanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCcBanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCcBanknameActionPerformed

    private void TCcbankroutingnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCcbankroutingnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCcbankroutingnumberActionPerformed

    private void TCcbankaccountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCcbankaccountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCcbankaccountnumberActionPerformed

    private void TCcaccountbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCcaccountbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCcaccountbalanceActionPerformed

    private void TCcaccounttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCcaccounttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCcaccounttypeActionPerformed

    private void checksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checksaveActionPerformed
        // TODO add your handling code here:
        
        product.setCBankname(TCcbankaccountnumber.getText());
        product.setCbankaccountnumber(TCcbankaccountnumber.getText());
        product.setCbankrouatingnumber(TCcbankroutingnumber.getText());
        product.setCaccountbalance(TCcaccountbalance.getText());
        product.setCaccounttype(TCcaccounttype.getText());
        
        JOptionPane.showMessageDialog(this,"saved!!");
      
        
    }//GEN-LAST:event_checksaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CcBANKname;
    private javax.swing.JLabel Ccaccountbalance;
    private javax.swing.JLabel Ccaccounttype;
    private javax.swing.JLabel Ccbankaccountnumber;
    private javax.swing.JLabel Ccbankroutingnumber;
    private javax.swing.JTextField TCcBankname;
    private javax.swing.JTextField TCcaccountbalance;
    private javax.swing.JTextField TCcaccounttype;
    private javax.swing.JTextField TCcbankaccountnumber;
    private javax.swing.JTextField TCcbankroutingnumber;
    private javax.swing.JLabel checkingheader;
    private javax.swing.JButton checksave;
    // End of variables declaration//GEN-END:variables
}
