/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.lab1;

/**
 *
 * @author visha
 */
public class Driver extends javax.swing.JPanel {
   
     
            

    /**
     * Creates new form Driver
     */
    lab1 product;
    public Driver(lab1 product) {
        initComponents();
        
        this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DriverHeader = new javax.swing.JLabel();
        Clicensenumber = new javax.swing.JLabel();
        Cdateofissue = new javax.swing.JLabel();
        Cdateodexp = new javax.swing.JLabel();
        Cbloodtype = new javax.swing.JLabel();
        Cpicture = new javax.swing.JLabel();
        Tlincensenumber = new javax.swing.JTextField();
        Tdateofissue = new javax.swing.JTextField();
        Tdateofexp = new javax.swing.JTextField();
        TBloodtype = new javax.swing.JTextField();
        DriverSave = new javax.swing.JButton();
        upload = new javax.swing.JButton();
        imageview = new javax.swing.JLabel();

        DriverHeader.setText("Driver’s license information");

        Clicensenumber.setText("License number");

        Cdateofissue.setText("Date it was issued");

        Cdateodexp.setText("Date of expiration");

        Cbloodtype.setText("Blood type");

        Cpicture.setText("Picture");

        Tlincensenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TlincensenumberActionPerformed(evt);
            }
        });

        DriverSave.setText("Save");
        DriverSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverSaveActionPerformed(evt);
            }
        });

        upload.setText("upload");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Clicensenumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tlincensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cdateofissue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tdateofissue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cdateodexp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tdateofexp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cbloodtype)
                                    .addComponent(Cpicture))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upload)
                                    .addComponent(TBloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DriverSave)
                            .addComponent(DriverHeader))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addGap(46, 46, 46)
                .addComponent(imageview, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(DriverHeader)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clicensenumber)
                    .addComponent(Tlincensenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cdateofissue)
                    .addComponent(Tdateofissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cdateodexp)
                    .addComponent(Tdateofexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbloodtype)
                    .addComponent(TBloodtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cpicture)
                    .addComponent(upload)
                    .addComponent(imageview, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DriverSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TlincensenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TlincensenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TlincensenumberActionPerformed

    private void DriverSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverSaveActionPerformed
        // TODO add your handling code here:
        product.setLicensenumber(Tlincensenumber.getText());
        product.setIssuedate(Tdateofissue.getText());
        product.setExpdate(Tdateofexp.getText());
        product.setBloodtype(TBloodtype.getText());
        product.setImage(imageview.getIcon());
      
        JOptionPane.showMessageDialog(this,"Saved!!");
        
        
    }//GEN-LAST:event_DriverSaveActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(null);
        if (selected == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String getselectedImage = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null, getselectedImage);
            ImageIcon imIco = new ImageIcon(getselectedImage);
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(imageview.getWidth(), imageview.getHeight(), Image.SCALE_SMOOTH);
            imageview.setIcon(new ImageIcon(imgFit));
        }

    }//GEN-LAST:event_uploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cbloodtype;
    private javax.swing.JLabel Cdateodexp;
    private javax.swing.JLabel Cdateofissue;
    private javax.swing.JLabel Clicensenumber;
    private javax.swing.JLabel Cpicture;
    private javax.swing.JLabel DriverHeader;
    private javax.swing.JButton DriverSave;
    private javax.swing.JTextField TBloodtype;
    private javax.swing.JTextField Tdateofexp;
    private javax.swing.JTextField Tdateofissue;
    private javax.swing.JTextField Tlincensenumber;
    private javax.swing.JLabel imageview;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
