/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.lab1;

/**
 *
 * @author visha
 */
public class driverView extends javax.swing.JPanel {

    /**
     * Creates new form driverView
     */
    lab1 product;
    public driverView(lab1 product) {
        initComponents();
        
        this.product = product;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VDheader = new javax.swing.JLabel();
        Vlicensenumber = new javax.swing.JLabel();
        Vdateofissue = new javax.swing.JLabel();
        Vdateofexp = new javax.swing.JLabel();
        VBloodtype = new javax.swing.JLabel();
        VPicture = new javax.swing.JLabel();
        TVlincensenumber = new javax.swing.JLabel();
        TVDateofissue = new javax.swing.JLabel();
        TVDateofexp = new javax.swing.JLabel();
        TVDbloodtype = new javax.swing.JLabel();
        Vimage = new javax.swing.JLabel();

        VDheader.setText("Driver’s license information");

        Vlicensenumber.setText("License number");

        Vdateofissue.setText("Date it was issued");

        Vdateofexp.setText("Date of expiration");

        VBloodtype.setText("Blood type");

        VPicture.setText("Picture");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Vdateofexp)
                    .addComponent(Vdateofissue, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VBloodtype, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vlicensenumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VPicture, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TVlincensenumber)
                            .addComponent(TVDateofissue)
                            .addComponent(TVDateofexp)
                            .addComponent(TVDbloodtype))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Vimage)
                        .addGap(112, 112, 112))))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(VDheader)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VDheader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vlicensenumber)
                    .addComponent(TVlincensenumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vdateofissue)
                    .addComponent(TVDateofissue))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vdateofexp)
                    .addComponent(TVDateofexp))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VBloodtype)
                    .addComponent(TVDbloodtype))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VPicture)
                    .addComponent(Vimage))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TVDateofexp;
    private javax.swing.JLabel TVDateofissue;
    private javax.swing.JLabel TVDbloodtype;
    private javax.swing.JLabel TVlincensenumber;
    private javax.swing.JLabel VBloodtype;
    private javax.swing.JLabel VDheader;
    private javax.swing.JLabel VPicture;
    private javax.swing.JLabel Vdateofexp;
    private javax.swing.JLabel Vdateofissue;
    private javax.swing.JLabel Vimage;
    private javax.swing.JLabel Vlicensenumber;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        
        
    TVlincensenumber.setText(product.getLicensenumber());
    TVDateofissue.setText(product.getIssuedate());
    TVDateofexp.setText(product.getExpdate());
    TVDbloodtype.setText(product.getBloodtype());
    Vimage.setIcon(product.getImage());
    
    
    }
}
