/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.lab1;

/**
 *
 * @author visha
 */
public class finalreport extends javax.swing.JPanel {

    /**
     * Creates new form finalreport
     */
    lab1 product;
    public finalreport(lab1 product) {
        initComponents();
        
        this.product = product;
        displayProduct();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tfirstname = new javax.swing.JLabel();
        Tlastname = new javax.swing.JLabel();
        TDOB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Tphonenumber = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        Tage = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Theight = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Tweight = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tssn = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Taddress = new javax.swing.JLabel();
        Tcity = new javax.swing.JLabel();
        Tstate = new javax.swing.JLabel();
        Tzipcode = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        TSbankname = new javax.swing.JLabel();
        TSbankroutingnumber = new javax.swing.JLabel();
        TSbankaccountnumber = new javax.swing.JLabel();
        TSaccountbalance = new javax.swing.JLabel();
        TSaccounttype = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        TCBankname = new javax.swing.JLabel();
        TCbankaccount = new javax.swing.JLabel();
        TCbankrouting = new javax.swing.JLabel();
        TCacountbalance = new javax.swing.JLabel();
        TCaccounttype = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Tmedicalrecord = new javax.swing.JLabel();
        TAlergy1 = new javax.swing.JLabel();
        TAlergy2 = new javax.swing.JLabel();
        TAlergy3 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        Tlicense = new javax.swing.JLabel();
        Tissuedate = new javax.swing.JLabel();
        Texpiredate = new javax.swing.JLabel();
        Tbloodtype = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        Vimage = new javax.swing.JLabel();

        jLabel1.setText("Final Report");

        jLabel2.setText("Demographic info");

        jLabel3.setText(" First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("DOB");

        jLabel9.setText("Phone Number");

        age.setText("Age");

        jLabel13.setText("Height");

        jLabel15.setText("Weight");

        jLabel17.setText("SNN");

        jLabel19.setText("Address information");

        jLabel20.setText("Street address");

        jLabel21.setText("City");

        jLabel22.setText("State");

        jLabel23.setText("Zip code");

        jLabel28.setText("Saving account information");

        jLabel29.setText("Bank name");

        jLabel30.setText("Bank routing number");

        jLabel31.setText("Bank account number");

        jLabel32.setText("Account balance");

        jLabel33.setText("Account type ");

        jLabel39.setText("Checking account information");

        jLabel40.setText("Bank name");

        jLabel41.setText("Bank account number");

        jLabel42.setText("Bank routing number ");

        jLabel43.setText("Account balance");

        jLabel44.setText("Account type");

        jLabel50.setText("Medical Record");

        jLabel51.setText("Medical record number");

        jLabel52.setText("Alergy1");

        jLabel53.setText("Alergy2");

        jLabel54.setText("Alergy3");

        jLabel59.setText("Driver lience info");

        jLabel60.setText("License number");

        jLabel61.setText("Date of issued");

        jLabel62.setText("Blood Type");

        jLabel63.setText("Date of Expire");

        jLabel68.setText("Picture");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(53, 53, 53)
                                .addComponent(TSbankroutingnumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TSbankname))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tzipcode))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tstate))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tcity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Taddress))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(239, 239, 239)
                                        .addComponent(jLabel39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel59)
                                        .addGap(80, 80, 80))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TSaccountbalance))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(age)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tage))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9))
                                        .addGap(91, 91, 91)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TDOB)
                                            .addComponent(Tlastname)
                                            .addComponent(Tfirstname)
                                            .addComponent(Tphonenumber)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Theight, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Tweight, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Tssn, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(213, 213, 213)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel44)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TCaccounttype))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel43)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TCacountbalance))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel40)
                                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TCbankrouting)
                                                    .addComponent(TCbankaccount)
                                                    .addComponent(TCBankname)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel50)
                                        .addGap(40, 40, 40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(224, 224, 224)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel60)
                                                    .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel62, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Tlicense, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Tissuedate, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Texpiredate, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Tbloodtype, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(jLabel53)
                                            .addComponent(jLabel51)
                                            .addComponent(jLabel54)
                                            .addComponent(jLabel52)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel68)
                                                .addGap(109, 109, 109)
                                                .addComponent(Vimage)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tmedicalrecord)
                                    .addComponent(TAlergy1)
                                    .addComponent(TAlergy2)
                                    .addComponent(TAlergy3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TSaccounttype)
                                    .addComponent(TSbankaccountnumber))))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tfirstname)
                    .addComponent(jLabel40)
                    .addComponent(TCBankname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tlastname)
                    .addComponent(jLabel41)
                    .addComponent(TCbankaccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TDOB)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCbankrouting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Tphonenumber)
                    .addComponent(jLabel43)
                    .addComponent(TCacountbalance))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(Tage)
                    .addComponent(jLabel44)
                    .addComponent(TCaccounttype))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Theight)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel50)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Tweight)
                    .addComponent(jLabel51)
                    .addComponent(Tmedicalrecord))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Tssn)
                    .addComponent(jLabel52)
                    .addComponent(TAlergy1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel53)
                    .addComponent(TAlergy2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Taddress)
                    .addComponent(jLabel54)
                    .addComponent(TAlergy3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(Tcity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(Tstate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel59)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Tzipcode)
                    .addComponent(jLabel60)
                    .addComponent(Tlicense))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel61)
                    .addComponent(Tissuedate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(TSbankname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(Texpiredate))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(TSbankroutingnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(Tbloodtype))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(TSbankaccountnumber)
                    .addComponent(jLabel68)
                    .addComponent(Vimage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(TSaccountbalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(TSaccounttype))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TAlergy1;
    private javax.swing.JLabel TAlergy2;
    private javax.swing.JLabel TAlergy3;
    private javax.swing.JLabel TCBankname;
    private javax.swing.JLabel TCaccounttype;
    private javax.swing.JLabel TCacountbalance;
    private javax.swing.JLabel TCbankaccount;
    private javax.swing.JLabel TCbankrouting;
    private javax.swing.JLabel TDOB;
    private javax.swing.JLabel TSaccountbalance;
    private javax.swing.JLabel TSaccounttype;
    private javax.swing.JLabel TSbankaccountnumber;
    private javax.swing.JLabel TSbankname;
    private javax.swing.JLabel TSbankroutingnumber;
    private javax.swing.JLabel Taddress;
    private javax.swing.JLabel Tage;
    private javax.swing.JLabel Tbloodtype;
    private javax.swing.JLabel Tcity;
    private javax.swing.JLabel Texpiredate;
    private javax.swing.JLabel Tfirstname;
    private javax.swing.JLabel Theight;
    private javax.swing.JLabel Tissuedate;
    private javax.swing.JLabel Tlastname;
    private javax.swing.JLabel Tlicense;
    private javax.swing.JLabel Tmedicalrecord;
    private javax.swing.JLabel Tphonenumber;
    private javax.swing.JLabel Tssn;
    private javax.swing.JLabel Tstate;
    private javax.swing.JLabel Tweight;
    private javax.swing.JLabel Tzipcode;
    private javax.swing.JLabel Vimage;
    private javax.swing.JLabel age;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        
    
       Taddress.setText(product.getStreetaddress());
       Tcity.setText(product.getCity());
       Tstate.setText(product.getState());
       Tzipcode.setText(product.getZipcode());
       Tfirstname.setText(product.getFristname());
       Tlastname.setText(product.getLastname());
       Tphonenumber.setText(product.getPhone());
       TDOB.setText(product.getDOB());
       Tage.setText(product.getAge());
       Theight.setText(product.getHeight());
       Tweight.setText(product.getWeight());
       Tssn.setText(product.getSSN());
       TSbankname.setText(product.getSBankname());
       TSbankaccountnumber.setText(product.getSbankaccountnumber());
       TSbankroutingnumber.setText(product.getSbankrouatingnumber());
       TSaccountbalance.setText(product.getSaccountbalance());
       TSaccounttype.setText(product.getSaccounttype());
       TCBankname.setText(product.getCBankname());
       TCbankaccount.setText(product.getCbankaccountnumber());
       TCbankrouting.setText(product.getCbankrouatingnumber());
       TCacountbalance.setText(product.getCaccountbalance());
       TCaccounttype.setText(product.getCaccounttype());
       Tmedicalrecord.setText(product.getMedicalnumber());
       TAlergy1.setText(product.getAlergy1());
       TAlergy2.setText(product.getAlergy2());
       TAlergy3.setText(product.getAlergy3());
       Tlicense.setText(product.getLicensenumber());
       Tissuedate.setText(product.getIssuedate());
       Texpiredate.setText(product.getExpdate());
       Tbloodtype.setText(product.getBloodtype());
       Vimage.setIcon(product.getImage());
    
    
    }
}
