/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.lab1;

/**
 *
 * @author visha
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    lab1 product;
    
    
    public mainframe() {
        initComponents();
        
        product = new lab1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        savingaccountcreate = new javax.swing.JButton();
        medicalview = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        finalreport = new javax.swing.JButton();
        Demo = new javax.swing.JLabel();
        saving = new javax.swing.JLabel();
        checking = new javax.swing.JLabel();
        driver = new javax.swing.JLabel();
        medical = new javax.swing.JLabel();
        democreate = new javax.swing.JButton();
        checkingcreate = new javax.swing.JButton();
        drivercreate = new javax.swing.JButton();
        medicalcreate = new javax.swing.JButton();
        addresscreate = new javax.swing.JButton();
        driverview = new javax.swing.JButton();
        checkingview = new javax.swing.JButton();
        savingview = new javax.swing.JButton();
        address = new javax.swing.JLabel();
        demoview = new javax.swing.JButton();
        addressview = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        savingaccountcreate.setText("Create");
        savingaccountcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingaccountcreateActionPerformed(evt);
            }
        });

        medicalview.setText("View");
        medicalview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalviewActionPerformed(evt);
            }
        });

        finalreport.setText("Final report");
        finalreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalreportActionPerformed(evt);
            }
        });

        Demo.setText(" Demographic Info");

        saving.setText("Saving account info");

        checking.setText(" Checking account info");

        driver.setText("Driver’s license info");

        medical.setText("             Medical Record");

        democreate.setText("Create");
        democreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                democreateActionPerformed(evt);
            }
        });

        checkingcreate.setText("Create");
        checkingcreate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                checkingcreateComponentResized(evt);
            }
        });
        checkingcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingcreateActionPerformed(evt);
            }
        });

        drivercreate.setText("Create");
        drivercreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivercreateActionPerformed(evt);
            }
        });

        medicalcreate.setText("Create");
        medicalcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalcreateActionPerformed(evt);
            }
        });

        addresscreate.setText("Create");
        addresscreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresscreateActionPerformed(evt);
            }
        });

        driverview.setText("View");
        driverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverviewActionPerformed(evt);
            }
        });

        checkingview.setText("View");
        checkingview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingviewActionPerformed(evt);
            }
        });

        savingview.setText("View");
        savingview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingviewActionPerformed(evt);
            }
        });

        address.setText("Address Info");

        demoview.setText("View");
        demoview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoviewActionPerformed(evt);
            }
        });

        addressview.setText("View");
        addressview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(Demo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(208, 208, 208)
                            .addComponent(address))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addresscreate)
                                        .addComponent(democreate))
                                    .addGap(92, 92, 92)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressview, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(demoview, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(savingaccountcreate)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(savingview, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(medicalcreate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(medicalview, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(drivercreate)
                                        .addGap(84, 84, 84)
                                        .addComponent(driverview, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(medical, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(saving))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(checking)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(checkingcreate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(checkingview, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(finalreport)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Demo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(democreate)
                    .addComponent(addressview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresscreate)
                    .addComponent(demoview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saving)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingaccountcreate)
                    .addComponent(savingview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checking)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkingcreate)
                    .addComponent(checkingview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drivercreate)
                    .addComponent(driverview))
                .addGap(11, 11, 11)
                .addComponent(medical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalcreate)
                    .addComponent(medicalview))
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(finalreport)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalreportActionPerformed
        // TODO add your handling code here:
        finalreport createPanel = new finalreport(product);
        jSplitPane1.setRightComponent(createPanel);
    }//GEN-LAST:event_finalreportActionPerformed

    private void savingaccountcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingaccountcreateActionPerformed
        // TODO add your handling code here:
        Saving createPanel = new Saving(product);
        jSplitPane1.setRightComponent(createPanel);
    }//GEN-LAST:event_savingaccountcreateActionPerformed

    private void democreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_democreateActionPerformed
        // TODO add your handling code here:
        
        Demographic createPanel = new Demographic(product);
        jSplitPane1.setRightComponent(createPanel);
    }//GEN-LAST:event_democreateActionPerformed

    private void checkingcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingcreateActionPerformed
        // TODO add your handling code here:
        Checking createPanel = new Checking(product);
        jSplitPane1.setRightComponent(createPanel);
    }//GEN-LAST:event_checkingcreateActionPerformed

    private void drivercreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivercreateActionPerformed
        // TODO add your handling code here:
        Driver createPanel = new Driver(product);
        jSplitPane1.setRightComponent(createPanel);
        
    }//GEN-LAST:event_drivercreateActionPerformed

    private void medicalcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalcreateActionPerformed
        // TODO add your handling code here:
        Medical createPanel = new Medical(product);
        jSplitPane1.setRightComponent(createPanel);
    }//GEN-LAST:event_medicalcreateActionPerformed

    private void addresscreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresscreateActionPerformed
        // TODO add your handling code here:
        Address createPanel = new Address(product);
        jSplitPane1.setRightComponent(createPanel);
    }//GEN-LAST:event_addresscreateActionPerformed

    private void checkingcreateComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_checkingcreateComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingcreateComponentResized

    private void demoviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoviewActionPerformed
        // TODO add your handling code here:
        demographicview viewPanel = new demographicview (product);
        jSplitPane1.setRightComponent(viewPanel);
        
    }//GEN-LAST:event_demoviewActionPerformed

    private void addressviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressviewActionPerformed
        // TODO add your handling code here:
        viewadress viewPanel = new viewadress(product);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_addressviewActionPerformed

    private void driverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverviewActionPerformed
        // TODO add your handling code here:
        driverView viewPanel = new driverView (product);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_driverviewActionPerformed

    private void savingviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingviewActionPerformed
        // TODO add your handling code here:
        savingview viewPanel = new savingview (product);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_savingviewActionPerformed

    private void checkingviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingviewActionPerformed
        // TODO add your handling code here:
        checkingview viewPanel = new checkingview (product);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_checkingviewActionPerformed

    private void medicalviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalviewActionPerformed
        // TODO add your handling code here:
        medicalview viewPanel = new medicalview (product);
        jSplitPane1.setRightComponent(viewPanel);
    }//GEN-LAST:event_medicalviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Demo;
    private javax.swing.JLabel address;
    private javax.swing.JButton addresscreate;
    private javax.swing.JButton addressview;
    private javax.swing.JLabel checking;
    private javax.swing.JButton checkingcreate;
    private javax.swing.JButton checkingview;
    private javax.swing.JButton democreate;
    private javax.swing.JButton demoview;
    private javax.swing.JLabel driver;
    private javax.swing.JButton drivercreate;
    private javax.swing.JButton driverview;
    private javax.swing.JButton finalreport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel medical;
    private javax.swing.JButton medicalcreate;
    private javax.swing.JButton medicalview;
    private javax.swing.JLabel saving;
    private javax.swing.JButton savingaccountcreate;
    private javax.swing.JButton savingview;
    // End of variables declaration//GEN-END:variables
}
