/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.lab1;

/**
 *
 * @author visha
 */
public class savingview extends javax.swing.JPanel {

    /**
     * Creates new form savingview
     */
    lab1 product;
    public savingview(lab1 product) {
        initComponents();
        
        this.product = product;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VSheader = new javax.swing.JLabel();
        VSBankname = new javax.swing.JLabel();
        VSBankroutingnumber = new javax.swing.JLabel();
        VSbankaccountnumber = new javax.swing.JLabel();
        VSaccountbalance = new javax.swing.JLabel();
        VSaccounttype = new javax.swing.JLabel();
        TVSbankname = new javax.swing.JLabel();
        TVSbankroutingnumber = new javax.swing.JLabel();
        TVSbankaccountnumber = new javax.swing.JLabel();
        TVSaccountbalance = new javax.swing.JLabel();
        TVSaccounttype = new javax.swing.JLabel();

        VSheader.setText("Saving account information");

        VSBankname.setText("Bank name");

        VSBankroutingnumber.setText(" Bank routing number");

        VSbankaccountnumber.setText("bank account number");

        VSaccountbalance.setText("account balance");

        VSaccounttype.setText("account type");

        TVSbankname.setText("jLabel7");

        TVSbankroutingnumber.setText("jLabel8");

        TVSbankaccountnumber.setText("jLabel9");

        TVSaccountbalance.setText("jLabel10");

        TVSaccounttype.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VSBankroutingnumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TVSbankroutingnumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VSBankname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TVSbankname))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VSbankaccountnumber)
                            .addComponent(VSaccountbalance)
                            .addComponent(VSaccounttype))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TVSbankaccountnumber)
                            .addComponent(TVSaccountbalance)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TVSaccounttype)))
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(VSheader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VSheader)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSBankname)
                    .addComponent(TVSbankname))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSBankroutingnumber)
                    .addComponent(TVSbankroutingnumber))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSbankaccountnumber)
                    .addComponent(TVSbankaccountnumber))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSaccountbalance)
                    .addComponent(TVSaccountbalance))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VSaccounttype)
                    .addComponent(TVSaccounttype))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TVSaccountbalance;
    private javax.swing.JLabel TVSaccounttype;
    private javax.swing.JLabel TVSbankaccountnumber;
    private javax.swing.JLabel TVSbankname;
    private javax.swing.JLabel TVSbankroutingnumber;
    private javax.swing.JLabel VSBankname;
    private javax.swing.JLabel VSBankroutingnumber;
    private javax.swing.JLabel VSaccountbalance;
    private javax.swing.JLabel VSaccounttype;
    private javax.swing.JLabel VSbankaccountnumber;
    private javax.swing.JLabel VSheader;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        
        
        TVSbankname.setText(product.getSBankname());
        TVSbankaccountnumber.setText(product.getSbankaccountnumber());
        TVSbankroutingnumber.setText(product.getSbankrouatingnumber());
        TVSaccountbalance.setText(product.getSaccountbalance());
        TVSaccounttype.setText(product.getSaccounttype());  
    
    
    
    }
}
