/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
import model.lab1;

/**
 *
 * @author visha
 */
public class Saving extends javax.swing.JPanel {

    /**
     * Creates new form Saving
     */
    lab1 product;
    public Saving(lab1 product) {
        initComponents();
        
        this.product =product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CSheader = new javax.swing.JLabel();
        CSbankname = new javax.swing.JLabel();
        CSbankroutingnumber = new javax.swing.JLabel();
        CSbankaccountnumber = new javax.swing.JLabel();
        CSAccountbalance = new javax.swing.JLabel();
        CSAccountType = new javax.swing.JLabel();
        CTbankname = new javax.swing.JTextField();
        CTbankroutingnumber = new javax.swing.JTextField();
        CTbankaccountnumber = new javax.swing.JTextField();
        CTaccountbalance = new javax.swing.JTextField();
        CTaccounttype = new javax.swing.JTextField();
        SavingSave = new javax.swing.JButton();

        CSheader.setText("Saving account information");

        CSbankname.setText("Bank name");

        CSbankroutingnumber.setText("Bank routing number");

        CSbankaccountnumber.setText("Bank account number");

        CSAccountbalance.setText("Account balance");

        CSAccountType.setText("Account Type");

        CTaccounttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTaccounttypeActionPerformed(evt);
            }
        });

        SavingSave.setText("Save");
        SavingSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(CSheader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSbankroutingnumber)
                                    .addComponent(CSbankname))
                                .addGap(227, 227, 227)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CTbankroutingnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(CTbankname)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CSAccountbalance)
                                    .addComponent(CSbankaccountnumber)
                                    .addComponent(CSAccountType))
                                .addGap(222, 222, 222)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CTaccounttype)
                                    .addComponent(CTbankaccountnumber)
                                    .addComponent(CTaccountbalance))))))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(SavingSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CSheader)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CSbankname)
                            .addComponent(CTbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(CSbankroutingnumber))
                    .addComponent(CTbankroutingnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSbankaccountnumber)
                    .addComponent(CTbankaccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSAccountbalance)
                    .addComponent(CTaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSAccountType)
                    .addComponent(CTaccounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(SavingSave)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CTaccounttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTaccounttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTaccounttypeActionPerformed

    private void SavingSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingSaveActionPerformed
        // TODO add your handling code here:
        product.setSBankname(CTbankaccountnumber.getText());
        product.setSbankaccountnumber(CTbankaccountnumber.getText());
        product.setSbankrouatingnumber(CTbankroutingnumber.getText());
        product.setSaccountbalance(CTaccountbalance.getText());
        product.setSaccounttype(CTaccounttype.getText());
        
        JOptionPane.showMessageDialog(this,"saved!!");
    }//GEN-LAST:event_SavingSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSAccountType;
    private javax.swing.JLabel CSAccountbalance;
    private javax.swing.JLabel CSbankaccountnumber;
    private javax.swing.JLabel CSbankname;
    private javax.swing.JLabel CSbankroutingnumber;
    private javax.swing.JLabel CSheader;
    private javax.swing.JTextField CTaccountbalance;
    private javax.swing.JTextField CTaccounttype;
    private javax.swing.JTextField CTbankaccountnumber;
    private javax.swing.JTextField CTbankname;
    private javax.swing.JTextField CTbankroutingnumber;
    private javax.swing.JButton SavingSave;
    // End of variables declaration//GEN-END:variables
}
